### ISSUE TITLE
input image mediastore ID

### ISSUE THREAD

**Issue by kilik128** [joshehlinger/wombo_extract#4]
how we got mediastore ID ? got this 

J:\reddle\wombo_extract-master\wombo_extract-master>C:\\Users\\Kilik\\AppData\\Local\\Programs\\Python\\Python37-

ArgumentParser(prog='run.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
Traceback (most recent call last):
  File "J:\\reddle\\wombo_extract-master\\wombo_extract-master\\run.py", line 75, in <module>
    sys.exit(main())
  File "J:\\reddle\\wombo_extract-master\\wombo_extract-master\\run.py", line 71, in main
    extractor.generate()
  File "J:\reddle\wombo_extract-master\wombo_extract-master\wombo\extract.py", line 179, in generate
    task_id = self.start_task()
  File "J:\reddle\wombo_extract-master\wombo_extract-master\wombo\extract.py", line 127, in start_task
    resp.raise_for_status()
  File "C:\Users\Kilik\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://paint.api.wombo.ai/api/v2/tasks'
For more information check: https://httpstatuses.com/422

**Comment by joshehlinger** [comment]
What arguments are you passing?

**Comment by kilik128** [comment]
"mediastore_id":"c85b73b6-57fa-4e84-bbed-74c383cc16ff"

**Comment by muad-dabs** [comment]
> "mediastore_id":"c85b73b6-57fa-4e84-bbed-74c383cc16ff"

Are you using a fresh upload? Wombo's server only stores input images for 48 hours.

**Comment by kilik128** [comment]
yes for sure we can upload directly with dream-api-1.1.0
